version: "3.8"

services:
    app:
        build: .
        container_name: produtos-app
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: produtos-db
        environment:
            POSTGRES_DB: db_produtos
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 1234
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
